import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { colors } from "@/design/tokens";
import "./globals.css";

// Self-hosted under the SIL Open Font License 1.1; see src/app/fonts/OFL-*.txt
// and THIRD_PARTY.md. Latin subset only. Fredoka is a variable font, so one
// file covers both display weights (500 and 600).
const fredoka = localFont({
  src: "./fonts/fredoka-latin-wght.woff2",
  weight: "500 600",
  display: "swap",
  variable: "--font-display",
});

const andika = localFont({
  src: [
    { path: "./fonts/andika-latin-400.woff2", weight: "400" },
    { path: "./fonts/andika-latin-700.woff2", weight: "700" },
  ],
  display: "swap",
  variable: "--font-text",
});

// Icons and the Open Graph image come from the file conventions next to this
// file (icon.svg, favicon.ico, apple-icon.png, opengraph-image.png), all
// regenerated by `pnpm brand:images`; metadataBase makes their URLs absolute.
export const metadata: Metadata = {
  metadataBase: new URL("https://ollie.rahatcodes.com"),
  title: "Ollie",
  description: "A Grade 1 math game that learns how you learn.",
  openGraph: {
    title: "Ollie",
    description: "A Grade 1 math game that learns how you learn.",
    siteName: "Ollie",
    type: "website",
    locale: "en_US",
  },
  twitter: { card: "summary_large_image" },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: colors.paper,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${fredoka.variable} ${andika.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
