#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Ollie: Cloudflare DNS + Coolify deploy for https://ollie.rahatcodes.com
# Reference: docs/deploy.md. Never Vercel.

TOTAL_STAGES=6

# Secrets live in Coolify. This file is only written if you opt in at stage 4.
ENV_FILE="${OLLIE_ENV_FILE:-.env.local}"

COOLIFY_URL=""
ANTHROPIC_API_KEY=""
ELEVENLABS_API_KEY=""

banner "Ollie deploy: Cloudflare + Coolify"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: DNS record for ollie.rahatcodes.com"
say "Point ollie.rahatcodes.com at the Hetzner host that runs Coolify."
open_url "https://dash.cloudflare.com"
step "Open the rahatcodes.com zone, then DNS → Records → Add record."
step "Type A, name 'ollie', IPv4 = the Hetzner host's public IP, Proxy status DNS only (grey cloud) for now."
note "DNS only lets Coolify's Traefik pass the HTTP-01 challenge and obtain the Let's Encrypt"
note "certificate on the first deploy. Stage 5 turns the proxy on once the certificate exists."
pause "Press Enter once the record is saved."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Coolify: create the resource from GitHub"
say "Coolify builds the Dockerfile at the repo root and runs the container."
ask COOLIFY_URL "Your Coolify base URL (e.g. https://coolify.example.com):"
COOLIFY_URL="${COOLIFY_URL%/}"
open_url "${COOLIFY_URL}/projects"
step "Pick (or create) a project and environment, then add a new resource."
step "Choose the GitHub source (public repository, or your GitHub App for push-to-deploy)"
step "and enter https://github.com/Rahat-ch/ollie, branch main."
step "Set Build Pack to 'Dockerfile' (not Nixpacks). The Dockerfile is at the repo root."
step "Set the exposed port to 3000."
step "Set the domain to https://ollie.rahatcodes.com."
step "If the resource has a health check section, set its path to /api/health on port 3000."
note "Do not deploy yet: storage and env vars come first so the first boot is correct."
pause "Press Enter once the resource is saved."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Coolify: persistent storage for generated audio"
say "Audio is written to /data/audio. A named volume keeps it across redeploys."
open_url "${COOLIFY_URL}/projects"
step "Open the ollie resource and find its persistent storage tab"
step "(Coolify labels it 'Storages' or 'Persistent Storage')."
step "Add a volume mount: name 'ollie-audio', destination path '/data/audio'."
step "Keep it a named volume, not a host directory bind mount."
pause "Press Enter once the volume is added."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Coolify: environment variables"
say "The two API keys live only in Coolify. They are never committed or baked into the image."
step "In the resource's environment variables tab, add ANTHROPIC_API_KEY"
step "(from https://console.anthropic.com/settings/keys)."
step "Add ELEVENLABS_API_KEY (ElevenLabs dashboard → profile → API keys)."
step "Mark both as runtime variables if asked; the build does not need them."
note "AUDIO_DIR is already /data/audio inside the image; no need to set it."
pause "Press Enter once both are saved in Coolify."
if confirm "Also keep a copy of both keys in ${ENV_FILE} for local dev? (default: no)"; then
  ask_secret ANTHROPIC_API_KEY "Paste ANTHROPIC_API_KEY:"
  ask_secret ELEVENLABS_API_KEY "Paste ELEVENLABS_API_KEY:"
  write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
  write_env ELEVENLABS_API_KEY "$ELEVENLABS_API_KEY"
  note "${ENV_FILE} is git-ignored (.env*) and excluded from the Docker build context."
else
  note "Nothing written locally."
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Deploy and verify"
say "Deploy from Coolify, then check the site and the health endpoint."
step "Click Deploy on the ollie resource and wait for the build log to finish."
pause "Press Enter once the deploy shows as finished."
open_url "https://ollie.rahatcodes.com"
step "The Ollie page should load over HTTPS with a valid Let's Encrypt certificate (no browser warning)."
pause "Press Enter once the certificate is valid."
open_url "https://dash.cloudflare.com"
step "Back in the rahatcodes.com zone: DNS → Records → edit 'ollie' → Proxy status Proxied (orange cloud)."
step "Then SSL/TLS → Overview → encryption mode Full (strict). The origin now has a valid certificate, so strict works."
note "If the site ever serves a certificate error after this, see docs/deploy.md (Cloudflare gotcha)."
pause "Press Enter once the proxy is on and the mode is Full (strict)."
open_url "https://ollie.rahatcodes.com/api/health"
step "The JSON must show \"ok\": true, \"audioDir\": \"/data/audio\", \"audioDirWritable\": true."
if ! confirm "Does /api/health report audioDirWritable: true?"; then
  SKIPPED+=("Fix the audio volume: /api/health reported audioDirWritable false (mount path must be /data/audio, as a named volume)")
  warn "Recorded for the summary; see docs/deploy.md, 'Persistent volume for audio'."
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Confirm the volume survives a redeploy"
say "Prove that ollie-audio is a real named volume and not recreated on each deploy."
step "On the Hetzner host (or in Coolify's terminal for the container), run:"
say "    docker exec <container> sh -c 'echo probe > /data/audio/.redeploy-probe'"
step "Trigger a redeploy in Coolify and wait for it to finish, then run:"
say "    docker exec <new-container> ls -la /data/audio"
step "Confirm .redeploy-probe is listed. (A green /api/health does not prove this: an anonymous volume is writable too.)"
if confirm "Is .redeploy-probe still present after the redeploy?"; then
  say "Volume confirmed. Remove the probe: docker exec <container> rm /data/audio/.redeploy-probe"
else
  SKIPPED+=("Volume did not survive redeploy: recheck the storage tab (name ollie-audio, path /data/audio, volume mount)")
  warn "Recorded for the summary."
fi

finish
