#!/usr/bin/env node
// Ollie's poses as a TypeScript module, so the rig renders inline and CSS can
// animate its parts (wings, eyes, beak; see public/ollie/README.md).
//
//   pnpm ollie:poses     rewrite src/ollie/poses.generated.ts from public/ollie/
//
// src/ollie/poses.test.ts fails when the module and the SVGs drift. The SVG
// files stay the source of truth; edit them and rerun.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const OLLIE_DIR = path.join(ROOT, "public", "ollie");
export const MODULE_PATH = path.join(ROOT, "src", "ollie", "poses.generated.ts");

/** The pose files, in the order of the README's table; the head is not a pose. */
export function readPoseSources(dir = OLLIE_DIR) {
  return Object.fromEntries(
    readdirSync(dir)
      .filter((file) => /^ollie-.*\.svg$/.test(file) && file !== "ollie-head.svg")
      .sort()
      .map((file) => [file.replace(/^ollie-|\.svg$/g, ""), readFileSync(path.join(dir, file), "utf8")]),
  );
}

/**
 * The markup inside the <svg> element, with each group's id turned into a
 * data-part attribute so several Ollies on one page never share an id.
 */
export function innerMarkup(svg) {
  const match = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>\s*$/);
  if (!match) throw new Error("not an SVG document");
  return match[1].trim().replace(/\bid="([^"]+)"/g, 'data-part="$1"');
}

export function renderModule(sources) {
  const entries = Object.entries(sources)
    .map(([pose, svg]) => `  "${pose}": ${JSON.stringify(innerMarkup(svg))},`)
    .join("\n");
  return [
    "// Generated by scripts/ollie-poses.mjs from public/ollie/*.svg. Do not edit;",
    "// run `pnpm ollie:poses` after changing a pose file.",
    "",
    `export type OlliePose = ${Object.keys(sources).map((pose) => `"${pose}"`).join(" | ")};`,
    "",
    '/** The markup inside each pose\'s <svg viewBox="0 0 240 240">, ids as data-part. */',
    "export const POSES: Readonly<Record<OlliePose, string>> = {",
    entries,
    "};",
    "",
  ].join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeFileSync(MODULE_PATH, renderModule(readPoseSources()));
  console.log(`wrote ${path.relative(ROOT, MODULE_PATH)}`);
}
